import { adminClient, allowedOrigins, cors, decryptToken, encryptToken, reply } from '../_shared/google-oauth.ts';
import { companyGoogleAccessToken } from '../_shared/company-google.ts';

type Input = { businessId?: string; accessToken?: string; limit?: number };
type Target = { storage_mode: 'client_owned' | 'company_owned'; client_spreadsheet_id: string | null; client_journal_sheet_id: number | null; client_journal_sheet_title: string | null; company_folder_id: string | null; company_spreadsheet_id: string | null; company_journal_sheet_id: number | null; company_journal_sheet_title: string | null };
const journalTab = 'Journal Entries';
const columns = ['MyLekhapal entry ID', 'Entry number', 'Date', 'Description', 'Line', 'Account code', 'Account name', 'Debit', 'Credit', 'Status'];
const google = async (token: string, url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json', ...(init?.headers || {}) } }); if (!response.ok) throw new Error(`google_api_${response.status}`); return response.status === 204 ? null : await response.json(); };
const audit = (admin: ReturnType<typeof adminClient>, businessId: string, target: Target, spreadsheetId: string, action: string, entryId?: string, reference?: string, worksheetId?: number, errorCode?: string) => admin.schema('private').from('google_journal_sync_audit').insert({ business_id: businessId, entry_id: entryId || null, target_mode: target.storage_mode, spreadsheet_id: spreadsheetId, worksheet_id: worksheetId || null, action, entry_reference: reference || null, error_code: errorCode || null });

async function refreshClientToken(admin: ReturnType<typeof adminClient>, id: string) {
  const { data: secret } = await admin.schema('private').from('workspace_google_connection_secrets').select('refresh_token_ciphertext').eq('connection_id', id).maybeSingle();
  const clientId = Deno.env.get('GOOGLE_CLIENT_ID'), clientSecret = Deno.env.get('GOOGLE_CLIENT_SECRET');
  if (!secret?.refresh_token_ciphertext || !clientId || !clientSecret) throw new Error('missing_google_refresh_credentials');
  const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'refresh_token', refresh_token: await decryptToken(secret.refresh_token_ciphertext), client_id: clientId, client_secret: clientSecret }) });
  const value = await response.json(); if (!response.ok || !value.access_token) throw new Error(`google_token_refresh_${response.status}`);
  await admin.schema('private').from('workspace_google_connection_secrets').update({ access_token_ciphertext: await encryptToken(value.access_token), access_token_expires_at: new Date(Date.now() + Number(value.expires_in || 3600) * 1000).toISOString(), rotated_at: new Date().toISOString() }).eq('connection_id', id);
  return String(value.access_token);
}

async function resolveTarget(token: string, admin: ReturnType<typeof adminClient>, businessId: string, target: Target) {
  if (target.storage_mode === 'client_owned' && target.client_spreadsheet_id) return { target, spreadsheetId: target.client_spreadsheet_id };
  if (target.storage_mode === 'client_owned') {
    const created = await google(token, 'https://sheets.googleapis.com/v4/spreadsheets', { method: 'POST', body: JSON.stringify({ properties: { title: `MyLekhapal Journal ${businessId}` }, sheets: [{ properties: { title: journalTab } }] }) });
    const spreadsheetId = String(created.spreadsheetId); const updated = { ...target, client_spreadsheet_id: spreadsheetId };
    await admin.from('business_google_journal_targets').update({ client_spreadsheet_id: spreadsheetId, updated_at: new Date().toISOString() }).eq('business_id', businessId); return { target: updated, spreadsheetId };
  }
  const root = Deno.env.get('GOOGLE_COMPANY_DRIVE_ROOT_FOLDER_ID'); if (!root) throw new Error('company_google_root_folder_not_configured');
  const folder = target.company_folder_id ? { id: target.company_folder_id } : await google(token, 'https://www.googleapis.com/drive/v3/files', { method: 'POST', body: JSON.stringify({ name: `MyLekhapal-${businessId}`, mimeType: 'application/vnd.google-apps.folder', parents: [root] }) });
  const created = target.company_spreadsheet_id ? { spreadsheetId: target.company_spreadsheet_id } : await google(token, 'https://sheets.googleapis.com/v4/spreadsheets', { method: 'POST', body: JSON.stringify({ properties: { title: `MyLekhapal Journal ${businessId}` }, sheets: [{ properties: { title: journalTab } }] }) });
  if (!target.company_spreadsheet_id) await google(token, `https://www.googleapis.com/drive/v3/files/${encodeURIComponent(String(created.spreadsheetId))}?addParents=${encodeURIComponent(String(folder.id))}&removeParents=root&fields=id`, { method: 'PATCH', body: '{}' });
  const updated = { ...target, company_folder_id: String(folder.id), company_spreadsheet_id: String(created.spreadsheetId) };
  await admin.from('business_google_journal_targets').update({ company_folder_id: updated.company_folder_id, company_spreadsheet_id: updated.company_spreadsheet_id, updated_at: new Date().toISOString() }).eq('business_id', businessId); return { target: updated, spreadsheetId: updated.company_spreadsheet_id! };
}

async function resolveJournalTab(token: string, admin: ReturnType<typeof adminClient>, businessId: string, target: Target, spreadsheetId: string) {
  const meta = await google(token, `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(spreadsheetId)}?fields=sheets.properties`);
  const storedId = target.storage_mode === 'client_owned' ? target.client_journal_sheet_id : target.company_journal_sheet_id;
  let properties = meta.sheets?.find((s: any) => s.properties.sheetId === storedId)?.properties || meta.sheets?.find((s: any) => s.properties.title === journalTab)?.properties;
  if (!properties) { const result = await google(token, `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(spreadsheetId)}:batchUpdate`, { method: 'POST', body: JSON.stringify({ requests: [{ addSheet: { properties: { title: journalTab } } }] }) }); properties = result.replies?.[0]?.addSheet?.properties; }
  if (!properties) throw new Error('journal_worksheet_unavailable');
  const update = target.storage_mode === 'client_owned' ? { client_journal_sheet_id: properties.sheetId, client_journal_sheet_title: properties.title } : { company_journal_sheet_id: properties.sheetId, company_journal_sheet_title: properties.title };
  await admin.from('business_google_journal_targets').update({ ...update, updated_at: new Date().toISOString() }).eq('business_id', businessId);
  const check = await google(token, `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(spreadsheetId)}/values/${encodeURIComponent(`${properties.title}!A1:J1`)}`);
  if (!check.values?.length) await google(token, `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(spreadsheetId)}/values/${encodeURIComponent(`${properties.title}!A1:J1`)}?valueInputOption=RAW`, { method: 'PUT', body: JSON.stringify({ values: [columns] }) });
  return properties as { sheetId: number; title: string };
}

Deno.serve(async (req: Request) => {
  const origin = req.headers.get('origin'); if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: cors(origin) }); if (req.method !== 'POST') return reply({ error: 'Method not allowed.' }, 405, origin); if (origin && !allowedOrigins.has(origin)) return reply({ error: 'Request origin rejected.' }, 403, origin);
  try {
    const input = await req.json() as Input, authorization = req.headers.get('authorization') || (input.accessToken ? `Bearer ${input.accessToken}` : ''); if (!authorization.startsWith('Bearer ') || !input.businessId) return reply({ error: 'Sign in and select a business.' }, 400, origin);
    const admin = adminClient(), { data: { user } } = await admin.auth.getUser(authorization.slice(7)); const { data: member } = user ? await admin.from('business_memberships').select('role').eq('business_id', input.businessId).eq('user_id', user.id).eq('status', 'active').maybeSingle() : { data: null }; if (!member || member.role === 'auditor') return reply({ error: 'Your role cannot sync this business journal.' }, 403, origin);
    const { data: saved } = await admin.from('business_google_journal_targets').select('*').eq('business_id', input.businessId).maybeSingle<Target>(); if (!saved) return reply({ connected: false, synced: 0, message: 'Choose a Google Sheets delivery location before syncing.' }, 200, origin);
    let token: string; if (saved.storage_mode === 'client_owned') { const { data: connection } = await admin.from('workspace_google_connections').select('id').eq('business_id', input.businessId).is('revoked_at', null).eq('sync_status', 'connected').maybeSingle(); if (!connection) return reply({ connected: false, synced: 0, message: 'Connect the client Google account before syncing.' }, 200, origin); try { token = await refreshClientToken(admin, connection.id); } catch (error) { await admin.from('workspace_google_connections').update({ sync_status: 'needs_reauthorization' }).eq('id', connection.id); throw error; } } else token = await companyGoogleAccessToken();
    const resolved = await resolveTarget(token, admin, input.businessId, saved); const tab = await resolveJournalTab(token, admin, input.businessId, resolved.target, resolved.spreadsheetId);
    const existing = await google(token, `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(resolved.spreadsheetId)}/values/${encodeURIComponent(`${tab.title}!A:A`)}`); const ids = new Set((existing.values || []).map((row: string[]) => row[0]));
    const { data: queued } = await admin.schema('private').from('google_journal_sync_queue').select('entry_id').eq('business_id', input.businessId).is('synced_at', null).order('queued_at').limit(Math.min(Math.max(Number(input.limit || 50), 1), 100)); let synced = 0;
    for (const item of queued || []) try { const { data: entry } = await admin.from('journal_entries').select('id,entry_number,transaction_date,description,status,journal_lines(line_no,debit,credit,chart_of_accounts(code,name))').eq('id', item.entry_id).eq('business_id', input.businessId).single(); if (!entry) throw new Error('journal_entry_not_found'); if (!ids.has(String(entry.id))) { const values = entry.journal_lines.map((line: any) => [String(entry.id), entry.entry_number, entry.transaction_date, entry.description, line.line_no, line.chart_of_accounts?.code || '', line.chart_of_accounts?.name || '', String(line.debit || 0), String(line.credit || 0), entry.status]); await google(token, `https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(resolved.spreadsheetId)}/values/${encodeURIComponent(`${tab.title}!A:J`)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`, { method: 'POST', body: JSON.stringify({ values }) }); await audit(admin, input.businessId, resolved.target, resolved.spreadsheetId, 'appended', entry.id, entry.entry_number, tab.sheetId); ids.add(String(entry.id)); } else await audit(admin, input.businessId, resolved.target, resolved.spreadsheetId, 'already_present', entry.id, entry.entry_number, tab.sheetId); await admin.schema('private').from('google_journal_sync_queue').update({ synced_at: new Date().toISOString(), attempts: 0, last_error_code: null }).eq('entry_id', item.entry_id); synced++; } catch (error) { const code = error instanceof Error ? error.message : 'sync_failed'; await admin.schema('private').from('google_journal_sync_queue').update({ attempts: 1, last_error_code: code }).eq('entry_id', item.entry_id); await audit(admin, input.businessId, resolved.target, resolved.spreadsheetId, 'failed', item.entry_id, undefined, tab.sheetId, code); }
    return reply({ connected: true, spreadsheetId: resolved.spreadsheetId, worksheetId: tab.sheetId, worksheetTitle: tab.title, synced, message: synced ? 'Journal entries were saved to the configured Google Sheet.' : 'Google Sheet is ready; no new entries need syncing.' }, 200, origin);
  } catch (error) { const code = error instanceof Error ? error.message : 'sync_failed'; console.error('google_journal_sync_failed', { code }); return reply({ error: code.startsWith('google_token_refresh_') ? 'Google authorisation needs renewal. Reconnect the client Google account; the journal entry is still safe.' : 'Journal sync could not be completed. Your journal entry remains safely saved in MyLekhapal.' }, 503, origin); }
});
